name: Build and deploy ASP.Net Core app to Azure Web App - SEP-G4-API

on:
  push:
    branches:
      - main
    paths:
      - 'Code/CarpentryWorkshopAPI/**'  
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Build with dotnet
        run: |
          cd Code/CarpentryWorkshopAPI
          dotnet build --configuration Release

      - name: dotnet publish
        run: |
          cd Code/CarpentryWorkshopAPI
          dotnet publish -c Release -o ./publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: |
            Code/CarpentryWorkshopAPI/publish

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Copy Excel file to wwwroot
        run: |
          cp ./Code/CarpentryWorkshopAPI/CarpentryWorkshopAPI/Sample.xlsx $WEBAPP_DIR/wwwroot/Sample.xlsx
        env:
          WEBAPP_DIR: ${{ steps.deploy-to-webapp.outputs.webapp-dir }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'SEP-G4-API'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_34A1F774D87146B7819FE77F5D5D7538 }}
          package: .
